### ISSUE TITLE
I try to run with mask_rcnn_coco.h5

### ISSUE THREAD

**Issue by NorthLatitudeOne** [bendangnuksung/mrcnn_serving_ready#1]
Hi , bendangnuksung, I try to run with mask_rcnn_coco.h5, but I got the error message as below:
`name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.721
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 9.10GiB
2019-04-15 08:51:08.395483: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-04-15 08:51:09.217262: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-15 08:51:09.222426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-04-15 08:51:09.225392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-04-15 08:51:09.228476: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8788 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
WARNING:tensorflow:From E:\Anaconda\lib\site-packages\tensorflow\python\ops\sparse_ops.py:1165: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    model.load_weights(H5_WEIGHT_PATH, by_name=True)
  File "F:\Code\mrcnn_serving_ready-master\model.py", line 2131, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, layers)
  File "E:\Anaconda\lib\site-packages\keras\engine\saving.py", line 1149, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #389 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc/kernel:0' shape=(1024, 24) dtype=float32_ref> has shape (1024, 24), but the saved weight has shape (1024, 324).`

**Comment by bendangnuksung** [comment]
@NorthLatitudeOne It was happening because COCO model uses a little different config. Made an update, you can convert 'mask_rcnn_coco.h5'. You just need open 'user_config.py' and set
```python
# Make it True if you want to use the provided coco weights
is_coco = True
```

**Comment by NorthLatitudeOne** [comment]
Hi Bendang , thanks for your help, the problem solved now after adding the config.

**Comment by buaacarzp** [comment]
> Hi Bendang , thanks for your help, the problem solved now after adding the config.

 Hi,are you ok now? did you completed the mrcnn_coco.h5 to pb file ? why I always failure.... please help me .
