### ISSUE TITLE
Can not convert to tflite (UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 3: invalid start byte)

### ISSUE THREAD

**Issue by davidvirdeforshh** [bendangnuksung/mrcnn_serving_ready#20]
I've converted my **h5** file to **pb** using `mrcnn_serving_ready` seemingly successfully. However when I try to convert my **saved_model.pb** it to a tflite lite, using `tflite_convert`, it crashes.

### user_config.py

```
is_coco = False

MODEL_DIR = '../export/'

H5_WEIGHT_PATH = '../export/mask_rcnn_me_cfg_0113.h5'

PATH_TO_SAVE_FROZEN_PB = '../export/frozen_model/'

FROZEN_NAME = 'mask_frozen_graph.pb'

PATH_TO_SAVE_TENSORFLOW_SERVING_MODEL = '../export/serving_model'

VERSION_NUMBER = 1

NUMBER_OF_CLASSES = 1

```

### Crash
(keras-gpu) PS C:\src\> tflite_convert --output_file .\export\foo.tflite --graph_def_file=saved_model.pb --input_arrays=input_image --output_arrays=mrcnn_bbox/Reshape
2019-09-02 11:00:15.382200: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2019-09-02 11:00:15.496843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 1660 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:01:00.0
2019-09-02 11:00:15.502449: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-09-02 11:00:15.505062: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-09-02 11:00:15.510887: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-09-02 11:00:15.514936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 1660 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:01:00.0
2019-09-02 11:00:15.527747: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-09-02 11:00:15.532083: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-09-02 11:00:16.162723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-02 11:00:16.166335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2019-09-02 11:00:16.168587: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2019-09-02 11:00:16.170862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4637 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
Ignore 'tcmalloc: large alloc' warnings.
Traceback (most recent call last):
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\tensorflow\lite\python\lite.py", line 608, in from_frozen_graph
    graph_def.ParseFromString(file_content)
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\message.py", line 187, in ParseFromString
    return self.MergeFromString(serialized)
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\python_message.py", line 1124, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\python_message.py", line 1189, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\decoder.py", line 723, in DecodeField
    if value._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\python_message.py", line 1189, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\decoder.py", line 702, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\python_message.py", line 1189, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\decoder.py", line 847, in DecodeMap
    if submsg._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\python_message.py", line 1176, in InternalParse
    buffer, new_pos, wire_type)  # pylint: disable=protected-access
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\decoder.py", line 948, in _DecodeUnknownField
    (data, pos) = _DecodeUnknownFieldSet(buffer, pos)
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\decoder.py", line 927, in _DecodeUnknownFieldSet
    (data, pos) = _DecodeUnknownField(buffer, pos, wire_type)
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\decoder.py", line 952, in _DecodeUnknownField
    raise _DecodeError('Wrong wire type in tag.')
google.protobuf.message.DecodeError: Wrong wire type in tag.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\.conda\envs\keras-gpu\Scripts\tflite_convert-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 503, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 499, in run_main
    _convert_tf1_model(tflite_flags)
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 124, in _convert_tf1_model
    converter = _get_toco_converter(flags)
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 111, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "C:\Users\me\.conda\envs\keras-gpu\lib\site-packages\tensorflow\lite\python\lite.py", line 615, in from_frozen_graph
    file_content = file_content.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 3: invalid start byte
(keras-gpu) PS C:\src\>

### saved_model.pb
https://drive.google.com/open?id=1_3RcuuTy1dXHmdVyYJU5RQLWG9Dg1KWc

### I also tried opening the file with tensorboard but that also failed:
(keras-gpu) PS C:\Users\oixx\src\parkshark> python .\import_pb_to_tensorboard.py --model_dir ./export/serving_model/1/saved_model.pb --log_dir .
2019-09-02 14:28:07.270170: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2019-09-02 14:28:07.368085: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 1660 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:01:00.0
2019-09-02 14:28:07.372248: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-09-02 14:28:07.374859: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-09-02 14:28:07.376887: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-09-02 14:28:07.385897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 1660 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:01:00.0
2019-09-02 14:28:07.389397: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-09-02 14:28:07.396890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-09-02 14:28:08.051391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-02 14:28:08.053953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2019-09-02 14:28:08.056163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2019-09-02 14:28:08.058340: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4637 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File ".\import_pb_to_tensorboard.py", line 86, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File ".\import_pb_to_tensorboard.py", line 67, in main
    import_to_tensorboard(FLAGS.model_dir, FLAGS.log_dir)
  File ".\import_pb_to_tensorboard.py", line 57, in import_to_tensorboard
    graph_def.ParseFromString(f.read())
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\message.py", line 187, in ParseFromString
    return self.MergeFromString(serialized)
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\python_message.py", line 1124, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\python_message.py", line 1189, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\decoder.py", line 723, in DecodeField
    if value._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\python_message.py", line 1189, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\decoder.py", line 702, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\python_message.py", line 1189, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\decoder.py", line 847, in DecodeMap
    if submsg._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\python_message.py", line 1176, in InternalParse
    buffer, new_pos, wire_type)  # pylint: disable=protected-access
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\decoder.py", line 948, in _DecodeUnknownField
    (data, pos) = _DecodeUnknownFieldSet(buffer, pos)
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\decoder.py", line 927, in _DecodeUnknownFieldSet
    (data, pos) = _DecodeUnknownField(buffer, pos, wire_type)
  File "C:\Users\oixx\.conda\envs\keras-gpu\lib\site-packages\google\protobuf\internal\decoder.py", line 952, in _DecodeUnknownField
    raise _DecodeError('Wrong wire type in tag.')
google.protobuf.message.DecodeError: Wrong wire type in tag.

Any ideas what could be wrong here?

**Comment by bendangnuksung** [comment]
Sorry! Have no solutions to convert to TFlite at the moment. Please do let me know if you find a way.

**Comment by davidvirdeforshh** [comment]
> Sorry! Have no solutions to convert to TFlite at the moment. Please do let me know if you find a way.
I see, thank you!
I'll let you know if I solve it.

**Comment by bendangnuksung** [comment]
Closing as it is feature support.
